function OUT = hyst_maxpsi_vs_polar_artificial()
% Plot max |psi| vs artificial polar from precomputed HYST data.
%
% Input MAT is generated by hysteresis_no_disturbation.m and must contain
% variable HYST with one entry per (T, artificial_polar).

clc; close all;

% =========================
% USER SETTINGS
% =========================
T_target = 6.4;
T_tol = 1e-8;
quantity = "psi";       % "psi" or "X"
plot_modes = ["overall"];  % choose from "fwd", "bwd", "overall"
FS = 16;

% =========================
% Select HYST MAT file
% =========================
default_dir = fullfile(pwd, "Matlab", "hyst_data");
if ~isfolder(default_dir)
    default_dir = pwd;
end

[fname, fpath] = uigetfile(fullfile(default_dir, "*.mat"), ...
    "Select hyst_allT_allArtificialPolar.mat");
if isequal(fname, 0)
    error("User cancelled.");
end

matfile = fullfile(fpath, fname);
S = load(matfile);

if ~isfield(S, "HYST")
    error("Selected MAT file does not contain variable HYST: %s", matfile);
end

HYST = S.HYST(:);

valid = arrayfun(@(x) scalar_field_(x, "T") && ...
    scalar_field_(x, "artificial_polar"), HYST);
entries = HYST(valid);

if isempty(entries)
    error("No valid HYST entries found in %s.", matfile);
end

E = entries(abs([entries.T] - T_target) <= T_tol);
if isempty(E)
    Tall = unique([entries.T]);
    error("No HYST entries found for T=%.6g K. Available T: %s", ...
        T_target, mat2str(Tall));
end

% If the same polar was saved more than once, keep the last one in HYST order.
[polar_unique, keep_idx] = unique([E.artificial_polar], "last");
E = E(keep_idx);
[polar_unique, ord] = sort(polar_unique(:));
E = E(ord);

np = numel(E);
maxPsi_fwd = nan(np,1);
maxPsi_bwd = nan(np,1);
maxPsi_all = nan(np,1);
maxPsi_plot = nan(np,1);
polarList_meV = polar_unique(:);

for ip = 1:np
    R = E(ip);
    [~, yf, ~, yb] = get_quantity_curves_(R, quantity);

    maxPsi_fwd(ip) = max(abs(yf(:)), [], "omitnan");
    maxPsi_bwd(ip) = max(abs(yb(:)), [], "omitnan");
    maxPsi_all(ip) = max([maxPsi_fwd(ip); maxPsi_bwd(ip)], [], "omitnan");

    if isfield(R, "psi_f_plot") && lower(string(quantity)) == "psi"
        maxPsi_plot(ip) = max([abs(R.psi_f_plot(:)); abs(R.psi_b_plot(:))], [], "omitnan");
    elseif isfield(R, "X_f_plot") && lower(string(quantity)) == "x"
        maxPsi_plot(ip) = max([abs(R.X_f_plot(:)); abs(R.X_b_plot(:))], [], "omitnan");
    else
        maxPsi_plot(ip) = maxPsi_all(ip);
    end
end

ok = isfinite(polarList_meV) & isfinite(maxPsi_all);
polarList_meV = polarList_meV(ok);
maxPsi_fwd = maxPsi_fwd(ok);
maxPsi_bwd = maxPsi_bwd(ok);
maxPsi_all = maxPsi_all(ok);
maxPsi_plot = maxPsi_plot(ok);
E = E(ok);

if isempty(polarList_meV)
    error("No finite max |%s| data found for T=%.6g K.", quantity, T_target);
end

plot_modes = normalize_plot_modes_(plot_modes);

% =========================
% Plot
% =========================
fig = figure("Color","w","Position",[100 100 850 620]);
ax = axes(fig);
hold(ax, "on"); box(ax, "on");

legend_items = strings(numel(plot_modes),1);
ileg = 0;
if any(plot_modes == "fwd")
    plot(ax, polarList_meV, maxPsi_fwd, "o-", ...
        "LineWidth",2.0, "MarkerSize",7);
    ileg = ileg + 1;
    legend_items(ileg) = "forward";
end
if any(plot_modes == "bwd")
    plot(ax, polarList_meV, maxPsi_bwd, "s--", ...
        "LineWidth",2.0, "MarkerSize",7);
    ileg = ileg + 1;
    legend_items(ileg) = "backward";
end
if any(plot_modes == "overall")
    plot(ax, polarList_meV, maxPsi_all, "d-", ...
        "LineWidth",2.2, "MarkerSize",7);
    ileg = ileg + 1;
    legend_items(ileg) = "overall";
end
legend_items = legend_items(1:ileg);

grid(ax, "on");
xlabel(ax, "artificial polar (meV)", "Interpreter","latex");
ylabel(ax, sprintf("max $|%s|$", latex_quantity_(quantity)), ...
    "Interpreter","latex");
title(ax, sprintf("Max $|%s|$ vs artificial polar, $T=%.4g\\,\\mathrm{K}$", ...
    latex_quantity_(quantity), T_target), ...
    "Interpreter","latex", "FontWeight","normal");
legend(ax, legend_items, "Location","best", "Interpreter","latex");

set(ax, ...
    "FontSize",FS, ...
    "TickLabelInterpreter","latex", ...
    "LineWidth",1.3, ...
    "TickDir","out");

% =========================
% Save next to selected MAT file
% =========================
out_dir = fullfile(fpath, "plot");
if ~exist(out_dir, "dir")
    mkdir(out_dir);
end

safe_q = regexprep(char(quantity), "[^A-Za-z0-9_]", "_");
safe_modes = char(strjoin(plot_modes, "_"));
out_png = fullfile(out_dir, sprintf( ...
    "max%s_%s_vs_polar_from_hyst_T%.4f.png", safe_q, safe_modes, T_target));
out_mat = fullfile(out_dir, sprintf( ...
    "max%s_%s_vs_polar_from_hyst_T%.4f.mat", safe_q, safe_modes, T_target));

exportgraphics(fig, out_png, "Resolution", 300);

OUT = struct();
OUT.matfile = string(matfile);
OUT.T_target = T_target;
OUT.T_tol = T_tol;
OUT.quantity = quantity;
OUT.plot_modes = plot_modes;
OUT.polarList_meV = polarList_meV;
OUT.maxPsi_fwd = maxPsi_fwd;
OUT.maxPsi_bwd = maxPsi_bwd;
OUT.maxPsi_all = maxPsi_all;
OUT.maxPsi_plot = maxPsi_plot;
OUT.entries = E;
OUT.png = string(out_png);
OUT.mat = string(out_mat);

save(out_mat, "OUT");

fprintf("\nLoaded HYST: %s\n", matfile);
fprintf("T = %.6g K | quantity = %s | entries = %d\n", ...
    T_target, quantity, numel(polarList_meV));
disp(table(polarList_meV, maxPsi_fwd, maxPsi_bwd, maxPsi_all, ...
    "VariableNames", ["polar_meV","max_fwd","max_bwd","max_all"]));
fprintf("Saved figure: %s\n", out_png);
fprintf("Saved data  : %s\n", out_mat);

end

function plot_modes = normalize_plot_modes_(plot_modes)

plot_modes = lower(string(plot_modes(:)));
plot_modes = plot_modes(plot_modes ~= "");
if isempty(plot_modes)
    error('plot_modes must include at least one of "fwd", "bwd", or "overall".');
end

alias_from = ["forward","backward","all"];
alias_to = ["fwd","bwd","overall"];
for ia = 1:numel(alias_from)
    plot_modes(plot_modes == alias_from(ia)) = alias_to(ia);
end

allowed = ["fwd","bwd","overall"];
bad = plot_modes(~ismember(plot_modes, allowed));
if ~isempty(bad)
    error("Unknown plot_modes value(s): %s", strjoin(unique(bad), ", "));
end

[~, id] = unique(plot_modes, "stable");
plot_modes = plot_modes(sort(id));

end

function [xf, yf, xb, yb] = get_quantity_curves_(R, quantity)

xf = R.dop_fwd(:);
xb = R.dop_bwd(:);

switch lower(string(quantity))
    case "psi"
        if isfield(R,"psi_f_plot") && isfield(R,"psi_b_plot")
            yf = R.psi_f_plot(:);
            yb = R.psi_b_plot(:);
        elseif isfield(R,"abspsi_fwd") && isfield(R,"abspsi_bwd")
            yf = R.abspsi_fwd(:);
            yb = R.abspsi_bwd(:);
        elseif isfield(R,"psi_fwd") && isfield(R,"psi_bwd")
            yf = abs(R.psi_fwd(:));
            yb = abs(R.psi_bwd(:));
        else
            error("Cannot find psi data in HYST entry.");
        end

    case "x"
        if isfield(R,"X_f_plot") && isfield(R,"X_b_plot")
            yf = R.X_f_plot(:);
            yb = R.X_b_plot(:);
        elseif isfield(R,"absX_fwd") && isfield(R,"absX_bwd")
            yf = R.absX_fwd(:);
            yb = R.absX_bwd(:);
        elseif isfield(R,"X_fwd") && isfield(R,"X_bwd")
            yf = abs(R.X_fwd(:));
            yb = abs(R.X_bwd(:));
        else
            error("Cannot find X data in HYST entry.");
        end

    otherwise
        error("quantity must be psi or X.");
end

end

function s = latex_quantity_(quantity)

switch lower(string(quantity))
    case "psi"
        s = "\psi";
    case "x"
        s = "X";
    otherwise
        s = char(quantity);
end

end

function tf = scalar_field_(R, fieldname)

tf = isfield(R, fieldname) && isscalar(R.(fieldname)) && ...
    isnumeric(R.(fieldname)) && isfinite(R.(fieldname));

end
